// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2sBCWSxhvkNT8acrO0slUTKUlVNoRhH4',
    appId: '1:774503890675:web:c03e33f2282bd0f3924186',
    messagingSenderId: '774503890675',
    projectId: 'housesync-firebase-20966',
    authDomain: 'housesync-firebase-20966.firebaseapp.com',
    storageBucket: 'housesync-firebase-20966.firebasestorage.app',
    measurementId: 'G-1LGHPD4CKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTZFictCbgOd52wekaobVXBJ7n2-9A27o',
    appId: '1:774503890675:android:14ae8bdefdf2f772924186',
    messagingSenderId: '774503890675',
    projectId: 'housesync-firebase-20966',
    storageBucket: 'housesync-firebase-20966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ZETBvtfPcmU1VhbHH5IOO-9QGbKBvBs',
    appId: '1:774503890675:ios:93d34d503903b632924186',
    messagingSenderId: '774503890675',
    projectId: 'housesync-firebase-20966',
    storageBucket: 'housesync-firebase-20966.firebasestorage.app',
    iosBundleId: 'com.example.sharedAccommodationManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ZETBvtfPcmU1VhbHH5IOO-9QGbKBvBs',
    appId: '1:774503890675:ios:93d34d503903b632924186',
    messagingSenderId: '774503890675',
    projectId: 'housesync-firebase-20966',
    storageBucket: 'housesync-firebase-20966.firebasestorage.app',
    iosBundleId: 'com.example.sharedAccommodationManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2sBCWSxhvkNT8acrO0slUTKUlVNoRhH4',
    appId: '1:774503890675:web:392080de2512d931924186',
    messagingSenderId: '774503890675',
    projectId: 'housesync-firebase-20966',
    authDomain: 'housesync-firebase-20966.firebaseapp.com',
    storageBucket: 'housesync-firebase-20966.firebasestorage.app',
    measurementId: 'G-8YE9PXHG88',
  );
}
